# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.TextField(default=b'\xe4\xb8\x96\xe7\x95\x8c\xe5\x90\x8d\xe6\xa0\xa1', verbose_name='\u673a\u6784\u6807\u7b7e'),
        ),
    ]
